#include "codegen.h"
#include <sstream>
#include <stdexcept>
#include <iomanip>

CodeGen::CodeGen() : indentLevel(0), hasIOPlus(false), hasFileOps(false), hasTime(false) {}

std::string CodeGen::indent() {
    return std::string(indentLevel * 4, ' ');
}

std::string CodeGen::mapType(const std::string& t) {
    if (t == "int")    return "long long";
    if (t == "float")  return "double";
    if (t == "char")   return "char";
    if (t == "string") return "std::string";
    if (t == "bool")   return "bool";
    if (t.empty())     return "auto";
    return t; // 用户自定义类型（类名）
}

std::string CodeGen::generate(ProgramNode* prog) {
    // 先扫描是否用到 IOPlus / 文件操作
    // 直接在生成时检测，先做两趟：第一趟生成体，第二趟加头
    // 简化：直接包含所有可能需要的头
    genProgram(prog);
    // 拼接最终输出
    std::ostringstream final_out;
    final_out << "// Generated by Wquick Compiler\n";
    final_out << "#include <iostream>\n";
    final_out << "#include <string>\n";
    final_out << "#include <vector>\n";
    final_out << "#include <fstream>\n";
    final_out << "#include <sstream>\n";
    final_out << "#include <cmath>\n";
    final_out << "#include <iomanip>\n";
    final_out << "#include <windows.h>\n";
    if (hasTime) {
        final_out << "#include <ctime>\n";
        final_out << "#include <chrono>\n";
        final_out << "#include <thread>\n";
        final_out << "\n// --- time library runtime ---\n";
        final_out << "static void sleep(long long t) { std::this_thread::sleep_for(std::chrono::seconds(t)); }\n";
        final_out << "static std::string getTime() {\n";
        final_out << "    std::time_t _t = std::time(nullptr);\n";
        final_out << "    char _buf[20];\n";
        final_out << "    std::strftime(_buf, sizeof(_buf), \"%Y-%m-%d %H:%M:%S\", std::localtime(&_t));\n";
        final_out << "    return std::string(_buf);\n";
        final_out << "}\n";
        final_out << "static double time() {\n";
        final_out << "    return (double)std::chrono::duration_cast<std::chrono::milliseconds>(\n";
        final_out << "        std::chrono::system_clock::now().time_since_epoch()).count() / 1000.0;\n";
        final_out << "}\n";
    }
    final_out << "\n";
    // IOplus runtime helpers
    final_out << "// --- IOPlus runtime ---\n";
    final_out << "static std::string _ioplus_prompt = \"\";\n";
    final_out << "struct _IOPlus {};\n";
    final_out << "static _IOPlus iplus;\n";
    final_out << "struct _OPlus {};\n";
    final_out << "static _OPlus oplus;\n\n";
    // ipluscfg helper
    final_out << "struct _IPlusCfg {\n";
    final_out << "    std::string prompt;\n";
    final_out << "} ipluscfg;\n\n";
    final_out << out.str();
    return final_out.str();
}

void CodeGen::genProgram(ProgramNode* prog) {
    // 先生成全局内容（类、函数、模板等），再生成main
    // 分两步：先找 start块，其他先输出
    StartBlockStmt* startBlock = nullptr;
    std::vector<Stmt*> globals;
    for (auto& s : prog->stmts) {
        if (s->kind == Stmt::Kind::StartBlock) {
            startBlock = static_cast<StartBlockStmt*>(s.get());
        } else {
            globals.push_back(s.get());
        }
    }
    for (auto* s : globals) genStmt(s);
    out << "\nint main() {\n";
    out << "    SetConsoleOutputCP(65001);\n";   // 强制 UTF-8 输出，解决中文乱码
    out << "    SetConsoleCP(65001);\n";          // 输入也用 UTF-8
    indentLevel = 1;
    if (startBlock) {
        for (auto& s : startBlock->body) genStmt(s.get());
    }
    out << "    system(\"pause\");\n";
    out << "    return 0;\n";
    out << "}\n";
    indentLevel = 0;
}

void CodeGen::genStmt(Stmt* s) {
    switch (s->kind) {
        case Stmt::Kind::ExprStmt:      genExprStmt(static_cast<ExprStmt*>(s)); break;
        case Stmt::Kind::VarDecl:       genVarDecl(static_cast<VarDeclStmt*>(s)); break;
        case Stmt::Kind::ArrayDecl:     genArrayDecl(static_cast<ArrayDeclStmt*>(s)); break;
        case Stmt::Kind::If:            genIf(static_cast<IfStmt*>(s)); break;
        case Stmt::Kind::Switch:        genSwitch(static_cast<SwitchStmt*>(s)); break;
        case Stmt::Kind::For:           genFor(static_cast<ForStmt*>(s)); break;
        case Stmt::Kind::While:         genWhile(static_cast<WhileStmt*>(s)); break;
        case Stmt::Kind::Loop:          genLoop(static_cast<LoopStmt*>(s)); break;
        case Stmt::Kind::Def:           genDef(static_cast<DefStmt*>(s)); break;
        case Stmt::Kind::Return:        genReturn(static_cast<ReturnStmt*>(s)); break;
        case Stmt::Kind::Break:         out << indent() << "break;\n"; break;
        case Stmt::Kind::Continue:      out << indent() << "continue;\n"; break;
        case Stmt::Kind::Output:        genOutput(static_cast<OutputStmt*>(s)); break;
        case Stmt::Kind::Input:         genInput(static_cast<InputStmt*>(s)); break;
        case Stmt::Kind::ImportStmt:    genImport(static_cast<ImportStmt*>(s)); break;
        case Stmt::Kind::File:          genFile(static_cast<FileStmt*>(s)); break;
        case Stmt::Kind::Template:      genTemplate(static_cast<TemplateStmt*>(s)); break;
        case Stmt::Kind::Namespace:     genNamespace(static_cast<NamespaceStmt*>(s)); break;
        case Stmt::Kind::Class:         genClass(static_cast<ClassStmt*>(s)); break;
        case Stmt::Kind::IOPlusInput:   genIOPlusInput(static_cast<IOPlusInputStmt*>(s)); break;
        case Stmt::Kind::IOPlusOutput:  genIOPlusOutput(static_cast<IOPlusOutputStmt*>(s)); break;
        case Stmt::Kind::StartBlock:    genStartBlock(static_cast<StartBlockStmt*>(s)); break;
        case Stmt::Kind::Block: {
            auto* b = static_cast<BlockStmt*>(s);
            for (auto& st : b->stmts) genStmt(st.get());
            break;
        }
        default: break;
    }
}

void CodeGen::genBlock(const std::vector<StmtPtr>& stmts) {
    out << indent() << "{\n";
    inc();
    for (auto& s : stmts) genStmt(s.get());
    dec();
    out << indent() << "}\n";
}

void CodeGen::genExprStmt(ExprStmt* s) {
    out << indent() << genExpr(s->expr.get()) << ";\n";
}

void CodeGen::genVarDecl(VarDeclStmt* s) {
    std::string cppType = mapType(s->typeName);
    // auto 没有初始值时 C++ 会报错；改为 std::string（input 读入的默认类型）
    if (cppType == "auto" && !s->init) cppType = "std::string";

    if (s->isConst) out << indent() << "const " << cppType;
    else            out << indent() << cppType;

    out << " " << s->name;
    if (s->init) {
        out << " = " << genExpr(s->init.get());
    }
    out << ";\n";
}

void CodeGen::genArrayDecl(ArrayDeclStmt* s) {
    std::string elemT = mapType(s->elemType);
    if (!s->initElements.empty()) {
        // let <int> arr = [1,2,3];
        out << indent() << "std::vector<" << elemT << "> " << s->name << " = {";
        for (size_t i = 0; i < s->initElements.size(); i++) {
            if (i) out << ", ";
            out << genExpr(s->initElements[i].get());
        }
        out << "};\n";
    } else if (s->sizeExpr) {
        // let <int> arr[5];
        out << indent() << "std::vector<" << elemT << "> " << s->name
            << "(" << genExpr(s->sizeExpr.get()) << ");\n";
    } else {
        out << indent() << "std::vector<" << elemT << "> " << s->name << ";\n";
    }
}

void CodeGen::genIf(IfStmt* s) {
    bool first = true;
    for (auto& branch : s->branches) {
        if (branch.cond) {
            if (first) out << indent() << "if (" << genExpr(branch.cond.get()) << ")\n";
            else       out << indent() << "else if (" << genExpr(branch.cond.get()) << ")\n";
        } else {
            out << indent() << "else\n";
        }
        out << indent() << "{\n";
        inc();
        for (auto& st : branch.body) genStmt(st.get());
        dec();
        out << indent() << "}\n";
        first = false;
    }
}

void CodeGen::genSwitch(SwitchStmt* s) {
    out << indent() << "switch (" << genExpr(s->subject.get()) << ")\n";
    out << indent() << "{\n";
    for (auto& c : s->cases) {
        if (c.value) {
            out << indent() << "case " << genExpr(c.value.get()) << ":\n";
        } else {
            out << indent() << "default:\n";
        }
        out << indent() << "{\n";
        inc();
        for (auto& st : c.body) genStmt(st.get());
        out << indent() << "break;\n";
        dec();
        out << indent() << "}\n";
    }
    out << indent() << "}\n";
}

void CodeGen::genFor(ForStmt* s) {
    out << indent() << "for (";
    // init
    if (s->init) {
        if (s->init->kind == Stmt::Kind::VarDecl) {
            auto* vd = static_cast<VarDeclStmt*>(s->init.get());
            out << mapType(vd->typeName) << " " << vd->name;
            if (vd->init) out << " = " << genExpr(vd->init.get());
        } else if (s->init->kind == Stmt::Kind::ExprStmt) {
            out << genExpr(static_cast<ExprStmt*>(s->init.get())->expr.get());
        }
    }
    out << "; ";
    out << genExpr(s->cond.get()) << "; ";
    out << genExpr(s->step.get()) << ")\n";
    out << indent() << "{\n";
    inc();
    for (auto& st : s->body) genStmt(st.get());
    dec();
    out << indent() << "}\n";
}

void CodeGen::genWhile(WhileStmt* s) {
    out << indent() << "while (" << genExpr(s->cond.get()) << ")\n";
    out << indent() << "{\n";
    inc();
    for (auto& st : s->body) genStmt(st.get());
    dec();
    out << indent() << "}\n";
}

void CodeGen::genLoop(LoopStmt* s) {
    out << indent() << "for (long long _loop_i = 0; _loop_i < ("
        << genExpr(s->count.get()) << "); _loop_i++)\n";
    out << indent() << "{\n";
    inc();
    for (auto& st : s->body) genStmt(st.get());
    dec();
    out << indent() << "}\n";
}

void CodeGen::genDef(DefStmt* s) {
    // 生成为模板函数（兼容 C++17，避免 auto 参数警告）
    if (!s->params.empty()) {
        out << "\ntemplate<";
        for (size_t i = 0; i < s->params.size(); i++) {
            if (i) out << ", ";
            out << "typename _T" << i;
        }
        out << ">\n";
    }
    out << "auto " << s->name << "(";
    for (size_t i = 0; i < s->params.size(); i++) {
        if (i) out << ", ";
        out << "_T" << i << " " << s->params[i];
    }
    out << ")\n{\n";
    inc();
    for (auto& st : s->body) genStmt(st.get());
    dec();
    out << "}\n";
}

void CodeGen::genReturn(ReturnStmt* s) {
    if (s->value) out << indent() << "return " << genExpr(s->value.get()) << ";\n";
    else          out << indent() << "return;\n";
}

void CodeGen::genOutput(OutputStmt* s) {
    out << indent() << "std::cout";
    for (auto& arg : s->args) {
        out << " << " << genExpr(arg.get());
    }
    out << ";\n";
}

void CodeGen::genInput(InputStmt* s) {
    if (s->prompt) {
        out << indent() << "std::cout << " << genExpr(s->prompt.get()) << ";\n";
    }
    if (s->target) {
        out << indent() << "std::cin >> " << genExpr(s->target.get()) << ";\n";
    }
}

void CodeGen::genImport(ImportStmt* s) {
    if (s->module == "0" || s->module.empty()) {
        out << "// import:0 (no import)\n";
    } else if (s->module == "IOplus" || s->module == "IOPlus") {
        out << "// import:IOplus\n";
    } else if (s->module == "time") {
        hasTime = true;
        out << "// import:time\n";
    } else {
        out << "// import:" << s->module << "\n";
    }
}

void CodeGen::genFile(FileStmt* s) {
    for (auto& op : s->ops) {
        if (op.op == "read") {
            // read:"filename","encoding",var
            std::string fname = op.args.size() > 0 ? genExpr(op.args[0].get()) : "\"\"";
            std::string var   = op.args.size() > 2 ? genExpr(op.args[2].get()) : "_dummy";
            out << indent() << "{\n";
            inc();
            out << indent() << "std::ifstream _f(" << fname << ");\n";
            out << indent() << "std::ostringstream _ss;\n";
            out << indent() << "_ss << _f.rdbuf();\n";
            out << indent() << var << " = _ss.str();\n";
            dec();
            out << indent() << "}\n";
        } else if (op.op == "write") {
            std::string fname   = op.args.size() > 0 ? genExpr(op.args[0].get()) : "\"\"";
            std::string content = op.args.size() > 2 ? genExpr(op.args[2].get()) : "\"\"";
            out << indent() << "{\n";
            inc();
            out << indent() << "std::ofstream _f(" << fname << ");\n";
            out << indent() << "_f << " << content << ";\n";
            dec();
            out << indent() << "}\n";
        } else if (op.op == "a") {
            std::string fname   = op.args.size() > 0 ? genExpr(op.args[0].get()) : "\"\"";
            std::string content = op.args.size() > 2 ? genExpr(op.args[2].get()) : "\"\"";
            out << indent() << "{\n";
            inc();
            out << indent() << "std::ofstream _f(" << fname << ", std::ios::app);\n";
            out << indent() << "_f << " << content << ";\n";
            dec();
            out << indent() << "}\n";
        }
    }
}

void CodeGen::genTemplate(TemplateStmt* s) {
    // 生成为 C++ struct
    templates.insert(s->name);
    out << "\nstruct " << s->name << " {\n";
    for (auto& f : s->fields) {
        out << "    " << mapType(f.typeName) << " " << f.name << ";\n";
    }
    out << "};\n\n";
}

void CodeGen::genNamespace(NamespaceStmt* s) {
    namespaces.insert(s->name);   // 记录命名空间名，MemberAccess 时用 ::
    out << "\nnamespace " << s->name << " {\n";
    inc();
    for (auto& st : s->body) genStmt(st.get());
    dec();
    out << "} // namespace " << s->name << "\n\n";
}

void CodeGen::genClass(ClassStmt* s) {
    out << "\nclass " << s->name;
    if (!s->parentClass.empty()) out << " : public " << s->parentClass;
    out << " {\npublic:\n";
    inc();
    // 字段
    for (auto& f : s->fields) {
        std::string ft = mapType(f.typeName);
        out << indent() << ft << " " << f.name;
        if (f.init) out << " = " << genExpr(f.init.get());
        out << ";\n";
    }
    // 如果有继承或有带参构造函数，补充一个默认构造函数，避免派生类调不到父类默认构造
    bool hasExplicitCtor = false;
    for (auto& m : s->methods) {
        if (m.isConstructor) { hasExplicitCtor = true; break; }
    }
    if (hasExplicitCtor) {
        // 生成默认无参构造函数（字段默认初始化）
        out << indent() << s->name << "() = default;\n";
    }
    // 方法
    for (auto& m : s->methods) {
        // 构造函数和普通方法都生成模板形式，避免 auto 参数
        if (!m.params.empty()) {
            out << indent() << "template<";
            for (size_t i = 0; i < m.params.size(); i++) {
                if (i) out << ", ";
                out << "typename _T" << i;
            }
            out << ">\n";
        }
        if (m.isConstructor) {
            out << indent() << s->name << "(";
        } else {
            out << indent() << "auto " << m.name << "(";
        }
        for (size_t i = 0; i < m.params.size(); i++) {
            if (i) out << ", ";
            out << "_T" << i << " " << m.params[i];
        }
        out << ")\n" << indent() << "{\n";
        inc();
        for (auto& st : m.body) genStmt(st.get());
        dec();
        out << indent() << "}\n";
    }
    dec();
    out << "};\n\n";
}

void CodeGen::genIOPlusInput(IOPlusInputStmt* s) {
    // 输出 ipluscfg.prompt 提示，再 cin >>
    out << indent() << "{\n";
    inc();
    out << indent() << "if (!ipluscfg.prompt.empty() && ipluscfg.prompt != \"0\")\n";
    out << indent() << "    std::cout << ipluscfg.prompt;\n";
    for (auto& t : s->targets) {
        out << indent() << "std::cin >> " << genExpr(t.get()) << ";\n";
    }
    dec();
    out << indent() << "}\n";
}

void CodeGen::genIOPlusOutput(IOPlusOutputStmt* s) {
    out << indent() << "std::cout";
    for (auto& v : s->values) {
        out << " << " << genExpr(v.get());
    }
    out << ";\n";
}

void CodeGen::genStartBlock(StartBlockStmt* s) {
    for (auto& st : s->body) genStmt(st.get());
}

// =================== 表达式生成 ===================
std::string CodeGen::genExpr(Expr* e) {
    switch (e->kind) {
        case Expr::Kind::IntLit: {
            auto* n = static_cast<IntLitExpr*>(e);
            return std::to_string(n->value) + "LL";
        }
        case Expr::Kind::FloatLit: {
            auto* n = static_cast<FloatLitExpr*>(e);
            std::ostringstream oss;
            oss << std::setprecision(10) << n->value;
            std::string s = oss.str();
            if (s.find('.') == std::string::npos) s += ".0";
            return s;
        }
        case Expr::Kind::StrLit: {
            auto* n = static_cast<StrLitExpr*>(e);
            // 重新转义
            std::string r = "\"";
            for (char c : n->value) {
                if (c == '"')  r += "\\\"";
                else if (c == '\\') r += "\\\\";
                else if (c == '\n') r += "\\n";
                else if (c == '\t') r += "\\t";
                else r += c;
            }
            r += "\"";
            return r;
        }
        case Expr::Kind::CharLit: {
            auto* n = static_cast<CharLitExpr*>(e);
            if (n->value == '\'') return "'\\''";
            if (n->value == '\\') return "'\\\\'";
            if (n->value == '\n') return "'\\n'";
            return std::string("'") + n->value + "'";
        }
        case Expr::Kind::BoolLit: {
            return static_cast<BoolLitExpr*>(e)->value ? "true" : "false";
        }
        case Expr::Kind::Ident: {
            return static_cast<IdentExpr*>(e)->name;
        }
        case Expr::Kind::BinOp: {
            auto* n = static_cast<BinOpExpr*>(e);
            return "(" + genExpr(n->left.get()) + " " + n->op + " " + genExpr(n->right.get()) + ")";
        }
        case Expr::Kind::UnaryOp: {
            auto* n = static_cast<UnaryOpExpr*>(e);
            return "(" + n->op + genExpr(n->operand.get()) + ")";
        }
        case Expr::Kind::Assign: {
            auto* n = static_cast<AssignExpr*>(e);
            return genExpr(n->target.get()) + " = " + genExpr(n->value.get());
        }
        case Expr::Kind::CompoundAssign: {
            auto* n = static_cast<CompoundAssignExpr*>(e);
            return genExpr(n->target.get()) + " " + n->op + " " + genExpr(n->value.get());
        }
        case Expr::Kind::Call: {
            auto* n = static_cast<CallExpr*>(e);
            std::string s = genExpr(n->callee.get()) + "(";
            for (size_t i = 0; i < n->args.size(); i++) {
                if (i) s += ", ";
                s += genExpr(n->args[i].get());
            }
            return s + ")";
        }
        case Expr::Kind::ArrayAccess: {
            auto* n = static_cast<ArrayAccessExpr*>(e);
            return genExpr(n->array.get()) + "[" + genExpr(n->index.get()) + "]";
        }
        case Expr::Kind::MemberAccess: {
            auto* n = static_cast<MemberAccessExpr*>(e);
            std::string obj = genExpr(n->object.get());
            // this 是指针，用 ->；命名空间用 ::；普通对象用 .
            if (n->object->kind == Expr::Kind::This) {
                return "this->" + n->member;
            }
            if (n->object->kind == Expr::Kind::Ident) {
                auto* id = static_cast<IdentExpr*>(n->object.get());
                if (namespaces.count(id->name)) {
                    return obj + "::" + n->member;
                }
            }
            return obj + "." + n->member;
        }
        case Expr::Kind::ArrayLit: {
            auto* n = static_cast<ArrayLitExpr*>(e);
            std::string s = "{";
            for (size_t i = 0; i < n->elements.size(); i++) {
                if (i) s += ", ";
                s += genExpr(n->elements[i].get());
            }
            return s + "}";
        }
        case Expr::Kind::TypeCast: {
            auto* n = static_cast<TypeCastExpr*>(e);
            std::string t = mapType(n->targetType);
            return "((" + t + ")(" + genExpr(n->operand.get()) + "))";
        }
        case Expr::Kind::This: return "this";
        case Expr::Kind::Super: {
            // super(args) —— C++ 构造函数不能直接调用父构造，此处生成占位注释
            return "/* super() */";
        }
        case Expr::Kind::StructInit: {
            // TypeName{field1, field2} → C++ 聚合初始化
            auto* n = static_cast<StructInitExpr*>(e);
            std::string typeName = genExpr(n->typeName.get());
            std::string s = typeName + "{";
            for (size_t i = 0; i < n->fields.size(); i++) {
                if (i) s += ", ";
                s += genExpr(n->fields[i].get());
            }
            return s + "}";
        }
        default:
            return "/* unknown expr */";
    }
}
